# Generated by Django 3.0.8 on 2020-07-20 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insta_backend', '0001_initial'),
        ('notification', '0003_auto_20200720_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='post',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='insta_backend.Post'),
        ),
    ]
