# Generated by Django 3.0.8 on 2020-07-21 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insta_backend', '0001_initial'),
        ('notification', '0005_notification_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('like', 'Like'), ('comment', 'Comment'), ('follow', 'Follow'), ('mention', 'Mention')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='post',
            field=models.ForeignKey(blank=True, default='None', on_delete=django.db.models.deletion.CASCADE, to='insta_backend.Post'),
        ),
    ]
