# Generated by Django 3.0.8 on 2020-07-21 19:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0008_auto_20200721_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='created_timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
