# Generated by Django 3.0.8 on 2020-07-08 20:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('insta_backend', '0003_auto_20200707_1823'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='timestamp',
            new_name='updated_timestamp',
        ),
        migrations.AddField(
            model_name='post',
            name='created_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
