# Generated by Django 3.0.8 on 2020-07-06 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='age',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
