# Generated by Django 3.0.8 on 2020-07-07 15:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20200706_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='following',
            field=models.ManyToManyField(related_name='_author_following_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
